# analytics/ml_signals.py
import numpy as np
import pandas as pd
from typing import Dict, List, Optional, Tuple, Any
from datetime import datetime, timedelta
from dataclasses import dataclass
import joblib
import asyncio
from sklearn.ensemble import RandomForestClassifier, GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import xgboost as xgb
import lightgbm as lgb
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import warnings
warnings.filterwarnings('ignore')

logger = logging.getLogger(__name__)

@dataclass
class TradingSignal:
    """Trading signal generated by ML models."""
    mint: str
    timestamp: datetime
    action: str  # BUY, SELL, HOLD
    confidence: float
    price_prediction: Optional[float]
    price_change_pct: Optional[float]
    rugpull_probability: float
    position_size_pct: float
    stop_loss_price: Optional[float]
    take_profit_price: Optional[float]
    features_used: Dict[str, float]

class MLSignalGenerator:
    """Generates trading signals using machine learning models."""
    
    def __init__(self, db_pool, redis_client):
        self.db = db_pool
        self.redis = redis_client
        self.models = {}
        self.scalers = {}
        self.encoders = {}
        self.is_trained = False
        self.feature_importance = {}
        
    async def initialize_models(self):
        """Initialize ML models."""
        # Price movement prediction (XGBoost)
        self.models['price_predictor'] = xgb.XGBClassifier(
            n_estimators=200,
            max_depth=6,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.8,
            objective='binary:logistic',
            random_state=42
        )
        
        # Price change regression (LightGBM)
        self.models['price_regressor'] = lgb.LGBMRegressor(
            n_estimators=150,
            max_depth=5,
            learning_rate=0.05,
            num_leaves=31,
            random_state=42
        )
        
        # Rugpull detection (Random Forest)
        self.models['rugpull_detector'] = RandomForestClassifier(
            n_estimators=200,
            max_depth=10,
            min_samples_split=5,
            min_samples_leaf=2,
            class_weight='balanced',
            random_state=42
        )
        
        # Deep learning model for complex patterns
        self.models['deep_predictor'] = self._create_deep_model()
        
        # Initialize scalers
        self.scalers['price'] = StandardScaler()
        self.scalers['volume'] = StandardScaler()
        self.scalers['momentum'] = StandardScaler()
        
        logger.info("ML models initialized")
    
    def _create_deep_model(self) -> nn.Module:
        """Create deep learning model."""
        class PricePredictor(nn.Module):
            def __init__(self, input_size=50, hidden_size=128):
                super().__init__()
                self.lstm = nn.LSTM(input_size, hidden_size, batch_first=True, bidirectional=True)
                self.attention = nn.MultiheadAttention(hidden_size * 2, num_heads=4)
                self.fc1 = nn.Linear(hidden_size * 2, 64)
                self.fc2 = nn.Linear(64, 32)
                self.fc3 = nn.Linear(32, 3)  # 3 classes: UP, DOWN, STABLE
                self.dropout = nn.Dropout(0.3)
                self.relu = nn.ReLU()
                
            def forward(self, x):
                lstm_out, _ = self.lstm(x)
                attn_out, _ = self.attention(lstm_out, lstm_out, lstm_out)
                x = attn_out[:, -1, :]
                x = self.dropout(self.relu(self.fc1(x)))
                x = self.dropout(self.relu(self.fc2(x)))
                x = self.fc3(x)
                return x
        
        return PricePredictor()
    
    async def train_models(self, days_history: int = 30):
        """Train all ML models on historical data."""
        logger.info(f"Training models on {days_history} days of historical data")
        
        # Fetch training data
        training_data = await self.fetch_training_data(days_history)
        
        if len(training_data) < 1000:
            logger.warning("Insufficient training data")
            return
        
        # Prepare features
        X, y_price, y_rugpull = self.prepare_training_features(training_data)
        
        # Split data
        X_train, X_test, y_train, y_test = train_test_split(
            X, y_price, test_size=0.2, random_state=42
        )
        
        # Train price predictor (classification)
        logger.info("Training price predictor...")
        self.models['price_predictor'].fit(X_train, y_train)
        
        # Evaluate
        y_pred = self.models['price_predictor'].predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred, average='weighted')
        recall = recall_score(y_test, y_pred, average='weighted')
        f1 = f1_score(y_test, y_pred, average='weighted')
        
        logger.info(f"Price predictor metrics - Accuracy: {accuracy:.3f}, "
                   f"Precision: {precision:.3f}, Recall: {recall:.3f}, F1: {f1:.3f}")
        
        # Feature importance
        self.feature_importance['price_predictor'] = dict(zip(
            self.feature_names,
            self.models['price_predictor'].feature_importances_
        ))
        
        # Train price regressor
        logger.info("Training price regressor...")
        y_reg = training_data['future_return'].values
        X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
            X, y_reg, test_size=0.2, random_state=42
        )
        
        self.models['price_regressor'].fit(X_train_reg, y_train_reg)
        
        # Train rugpull detector
        logger.info("Training rugpull detector...")
        X_train_rp, X_test_rp, y_train_rp, y_test_rp = train_test_split(
            X, y_rugpull, test_size=0.2, random_state=42, stratify=y_rugpull
        )
        
        self.models['rugpull_detector'].fit(X_train_rp, y_train_rp)
        
        # Cross-validation
        cv_scores = cross_val_score(
            self.models['rugpull_detector'], X_train_rp, y_train_rp, cv=5, scoring='roc_auc'
        )
        logger.info(f"Rugpull detector CV AUC: {cv_scores.mean():.3f} (+/- {cv_scores.std():.3f})")
        
        self.is_trained = True
        
        # Save models
        await self.save_models()
        
        logger.info("Model training completed")
    
    def prepare_training_features(
        self, 
        data: pd.DataFrame
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Prepare features for training."""
        self.feature_names = []
        features = []
        
        # Group by token
        for mint, group in data.groupby('mint'):
            if len(group) < 50:
                continue
            
            token_features = self.engineer_features(group)
            features.append(token_features)
        
        if not features:
            return np.array([]), np.array([]), np.array([])
        
        X = np.vstack(features)
        
        # Target variables
        y_price = (data.groupby('mint')['future_price_change'].first() > 0.02).astype(int)
        y_rugpull = data.groupby('mint')['was_rugpulled'].first().fillna(0).astype(int)
        
        return X, y_price.values, y_rugpull.values
    
    def engineer_features(self, df: pd.DataFrame) -> np.ndarray:
        """Engineer features from raw data."""
        features = []
        
        # Price-based features
        features.extend(self._price_features(df))
        
        # Volume features
        features.extend(self._volume_features(df))
        
        # Momentum features
        features.extend(self._momentum_features(df))
        
        # Technical indicators
        features.extend(self._technical_indicators(df))
        
        # Market microstructure features
        features.extend(self._microstructure_features(df))
        
        # Social/sentiment features
        features.extend(self._sentiment_features(df))
        
        return np.array(features)
    
    def _price_features(self, df: pd.DataFrame) -> List[float]:
        """Extract price-based features."""
        features = []
        price = df['price'].values
        
        if len(price) > 0:
            # Returns
            returns = np.diff(np.log(price))
            
            features.append(returns[-1] if len(returns) > 0 else 0)  # Latest return
            features.append(np.mean(returns[-10:]) if len(returns) >= 10 else 0)  # 10-period mean return
            features.append(np.std(returns[-20:]) if len(returns) >= 20 else 0)  # 20-period volatility
            
            # Price relative to moving averages
            ma_10 = np.mean(price[-10:]) if len(price) >= 10 else price[-1]
            ma_50 = np.mean(price[-50:]) if len(price) >= 50 else price[-1]
            
            features.append(price[-1] / ma_10 - 1)  # Distance from MA10
            features.append(price[-1] / ma_50 - 1)  # Distance from MA50
            
            # Recent high/low
            high_20 = np.max(price[-20:]) if len(price) >= 20 else price[-1]
            low_20 = np.min(price[-20:]) if len(price) >= 20 else price[-1]
            
            features.append(price[-1] / high_20)  # Distance from recent high
            features.append(price[-1] / low_20 - 1)  # Distance from recent low
            
        else:
            features.extend([0] * 7)
        
        return features
    
    def _volume_features(self, df: pd.DataFrame) -> List[float]:
        """Extract volume-based features."""
        features = []
        
        if 'volume_1h' in df.columns:
            volume = df['volume_1h'].values
            
            if len(volume) > 0:
                features.append(volume[-1])
                features.append(np.mean(volume[-5:]) if len(volume) >= 5 else volume[-1])
                features.append(volume[-1] / max(np.mean(volume[-20:]), 1e-9))  # Volume ratio
            else:
                features.extend([0, 0, 0])
        
        return features
    
    def _momentum_features(self, df: pd.DataFrame) -> List[float]:
        """Extract momentum features."""
        features = []
        
        if 'momentum_score' in df.columns:
            score = df['momentum_score'].values
            features.append(score[-1] if len(score) > 0 else 50)
            features.append(np.mean(score[-5:]) if len(score) >= 5 else 50)
        else:
            features.extend([50, 50])
        
        return features
    
    def _technical_indicators(self, df: pd.DataFrame) -> List[float]:
        """Calculate technical indicators."""
        features = []
        price = df['price'].values
        
        if len(price) >= 14:
            # RSI
            rsi = self._calculate_rsi(price[-14:])
            features.append(rsi)
            
            # MACD
            macd, signal = self._calculate_macd(price)
            features.append(macd)
            features.append(signal)
            
            # Bollinger Bands position
            bb_position = self._calculate_bb_position(price[-20:])
            features.append(bb_position)
        else:
            features.extend([50, 0, 0, 0])
        
        return features
    
    def _calculate_rsi(self, prices: np.ndarray, period: int = 14) -> float:
        """Calculate RSI indicator."""
        deltas = np.diff(prices)
        seed = deltas[:period+1]
        up = seed[seed >= 0].sum() / period
        down = -seed[seed < 0].sum() / period
        
        if down == 0:
            return 100.0
        
        rs = up / down
        rsi = 100 - (100 / (1 + rs))
        return rsi
    
    def _calculate_macd(self, prices: np.ndarray) -> Tuple[float, float]:
        """Calculate MACD indicator."""
        exp1 = pd.Series(prices).ewm(span=12, adjust=False).mean()
        exp2 = pd.Series(prices).ewm(span=26, adjust=False).mean()
        macd = exp1 - exp2
        signal = macd.ewm(span=9, adjust=False).mean()
        
        return macd.iloc[-1], signal.iloc[-1]
    
    def _calculate_bb_position(self, prices: np.ndarray) -> float:
        """Calculate position within Bollinger Bands."""
        sma = np.mean(prices)
        std = np.std(prices)
        
        upper_band = sma + 2 * std
        lower_band = sma - 2 * std
        
        if upper_band == lower_band:
            return 0.5
        
        position = (prices[-1] - lower_band) / (upper_band - lower_band)
        return np.clip(position, 0, 1)
    
    def _microstructure_features(self, df: pd.DataFrame) -> List[float]:
        """Extract market microstructure features."""
        features = []
        
        if 'liquidity' in df.columns and 'market_cap' in df.columns:
            liquidity = df['liquidity'].values[-1]
            market_cap = df['market_cap'].values[-1]
            
            features.append(liquidity / max(market_cap, 1e-9))  # Liquidity ratio
        else:
            features.append(0)
        
        if 'holder_count' in df.columns:
            features.append(df['holder_count'].values[-1])
        else:
            features.append(0)
        
        return features
    
    def _sentiment_features(self, df: pd.DataFrame) -> List[float]:
        """Extract sentiment features."""
        features = []
        
        if 'social_score' in df.columns:
            features.append(df['social_score'].values[-1])
        else:
            features.append(0)
        
        return features
    
    async def generate_signals(self, token_data: Dict[str, pd.DataFrame]) -> Dict[str, TradingSignal]:
        """Generate trading signals for all monitored tokens."""
        if not self.is_trained:
            logger.warning("Models not trained yet")
            return {}
        
        signals = {}
        
        for mint, df in token_data.items():
            if len(df) < 50:
                continue
            
            signal = await self.generate_single_signal(mint, df)
            if signal:
                signals[mint] = signal
        
        return signals
    
    async def generate_single_signal(self, mint: str, df: pd.DataFrame) -> Optional[TradingSignal]:
        """Generate trading signal for a single token."""
        try:
            # Engineer features
            features = self.engineer_features(df)
            
            if len(features) == 0:
                return None
            
            features_reshaped = features.reshape(1, -1)
            
            # Get predictions from all models
            price_pred_proba = self.models['price_predictor'].predict_proba(features_reshaped)[0]
            price_change_pred = self.models['price_regressor'].predict(features_reshaped)[0]
            rugpull_proba = self.models['rugpull_detector'].predict_proba(features_reshaped)[0][1]
            
            # Determine action
            if price_pred_proba[1] > 0.6 and rugpull_proba < 0.3:
                action = "BUY"
                confidence = price_pred_proba[1] * (1 - rugpull_proba)
            elif price_pred_proba[0] > 0.6:
                action = "SELL"
                confidence = price_pred_proba[0]
            else:
                action = "HOLD"
                confidence = 0.5
            
            # Calculate position size using Kelly Criterion
            win_prob = max(price_pred_proba[1], 0.5)
            avg_win = self.get_avg_win()
            avg_loss = self.get_avg_loss()
            
            if avg_loss > 0:
                kelly = (win_prob * avg_win - (1 - win_prob) * avg_loss) / (avg_win * avg_loss)
                position_size = max(0, min(0.25, kelly)) * (1 - rugpull_proba)
            else:
                position_size = 0
            
            # Calculate stop loss and take profit
            current_price = df['price'].iloc[-1]
            stop_loss = current_price * 0.9 if action == "BUY" else None
            take_profit = current_price * 1.3 if action == "BUY" else None
            
            return TradingSignal(
                mint=mint,
                timestamp=datetime.now(),
                action=action,
                confidence=float(confidence),
                price_prediction=float(current_price * (1 + price_change_pred)),
                price_change_pct=float(price_change_pred * 100),
                rugpull_probability=float(rugpull_proba),
                position_size_pct=float(position_size),
                stop_loss_price=stop_loss,
                take_profit_price=take_profit,
                features_used=self.get_top_features(features)
            )
            
        except Exception as e:
            logger.error(f"Error generating signal for {mint}: {e}")
            return None
    
    def get_top_features(self, features: np.ndarray, top_n: int = 10) -> Dict[str, float]:
        """Get top contributing features."""
        if not self.feature_importance:
            return {}
        
        importance = self.feature_importance.get('price_predictor', {})
        sorted_features = sorted(importance.items(), key=lambda x: x[1], reverse=True)[:top_n]
        
        return dict(sorted_features)
    
    def get_avg_win(self) -> float:
        """Get average winning trade percentage."""
        # Cache this value
        cache_key = "ml:avg_win"
        cached = self.redis.get(cache_key)
        if cached:
            return float(cached)
        
        return 0.15  # Default 15%
    
    def get_avg_loss(self) -> float:
        """Get average losing trade percentage."""
        cache_key = "ml:avg_loss"
        cached = self.redis.get(cache_key)
        if cached:
            return float(cached)
        
        return 0.10  # Default 10%
    
    async def fetch_training_data(self, days: int) -> pd.DataFrame:
        """Fetch training data from database."""
        async with self.db.acquire() as conn:
            rows = await conn.fetch("""
                WITH token_features AS (
                    SELECT 
                        tm.mint,
                        tm.timestamp,
                        tm.price,
                        tm.volume_1h,
                        tm.volume_24h,
                        tm.liquidity,
                        tm.market_cap,
                        tm.holder_count,
                        tm.buy_count_1h,
                        tm.sell_count_1h,
                        tm.momentum_score,
                        tm.risk_score,
                        tm.social_score,
                        t.was_rugpulled,
                        LEAD(tm.price, 60) OVER (PARTITION BY tm.mint ORDER BY tm.timestamp) as future_price,
                        (LEAD(tm.price, 60) OVER (PARTITION BY tm.mint ORDER BY tm.timestamp) - tm.price) 
                            / NULLIF(tm.price, 0) as future_return,
                        CASE 
                            WHEN (LEAD(tm.price, 60) OVER (PARTITION BY tm.mint ORDER BY tm.timestamp) - tm.price) 
                                / NULLIF(tm.price, 0) > 0.02 THEN 1 
                            ELSE 0 
                        END as future_price_up
                    FROM token_metrics tm
                    JOIN tokens t ON tm.mint = t.mint
                    WHERE tm.timestamp >= NOW() - INTERVAL '1 day' * $1
                )
                SELECT * FROM token_features
                WHERE future_price IS NOT NULL
                ORDER BY mint, timestamp
            """, days)
            
            return pd.DataFrame([dict(r) for r in rows])
    
    async def save_models(self):
        """Save trained models to disk."""
        import joblib
        
        model_dir = Path("models")
        model_dir.mkdir(exist_ok=True)
        
        # Save sklearn-compatible models
        joblib.dump(self.models['price_predictor'], model_dir / "price_predictor.pkl")
        joblib.dump(self.models['price_regressor'], model_dir / "price_regressor.pkl")
        joblib.dump(self.models['rugpull_detector'], model_dir / "rugpull_detector.pkl")
        
        # Save scalers
        joblib.dump(self.scalers, model_dir / "scalers.pkl")
        
        # Save feature importance
        with open(model_dir / "feature_importance.json", "w") as f:
            json.dump(self.feature_importance, f)
        
        # Save PyTorch model
        torch.save(
            self.models['deep_predictor'].state_dict(),
            model_dir / "deep_predictor.pt"
        )
        
        logger.info("Models saved to disk")
    
    async def load_models(self):
        """Load trained models from disk."""
        import joblib
        
        model_dir = Path("models")
        
        if not model_dir.exists():
            logger.warning("No saved models found")
            return False
        
        try:
            # Load sklearn models
            self.models['price_predictor'] = joblib.load(model_dir / "price_predictor.pkl")
            self.models['price_regressor'] = joblib.load(model_dir / "price_regressor.pkl")
            self.models['rugpull_detector'] = joblib.load(model_dir / "rugpull_detector.pkl")
            
            # Load scalers
            self.scalers = joblib.load(model_dir / "scalers.pkl")
            
            # Load feature importance
            with open(model_dir / "feature_importance.json", "r") as f:
                self.feature_importance = json.load(f)
            
            # Load PyTorch model
            self.models['deep_predictor'].load_state_dict(
                torch.load(model_dir / "deep_predictor.pt")
            )
            
            self.is_trained = True
            logger.info("Models loaded from disk")
            return True
            
        except Exception as e:
            logger.error(f"Error loading models: {e}")
            return False